### ISSUE TITLE
Identify which user is connected

### ISSUE THREAD

**Issue by AtleC** [HavenDV/H.Pipes#7]
Hi,

In System.IO.Pipes there is a function "GetImpersonationUserName()" for getting the username of the user connecting.
Have you looked into adding similar capabilities? 

This would need to be handled server side to avoid the possibility of a user impersonating another user.

**Comment by HavenDV** [comment]
Added in the latest release. Usage:
```csharp
server.ClientConnected += async (o, args) =>
{
    var name = args.Connection.GetImpersonationUserName();

    Console.WriteLine($"Client {name} is now connected!");
};
```

**Comment by AtleC** [comment]
Nice!

It seems like there is an issue with the latest version (1.15.8) in nuget tho:
![image](https://user-images.githubusercontent.com/46347347/143432990-bbbd1398-d222-4fb0-a334-ba88e60363f8.png)

I get this when trying to debug in Visual studio 2022, with 1.15.6 it works

**Comment by AtleC** [comment]
Did some more testing, it works fine when running the client and server in different instances of Visual Studio.
I guess this is because the refactoring you did in [ff9f6bb99698e0493b40ec762a5dba7ee2cad528](https://github.com/HavenDV/H.Pipes/commit/ff9f6bb99698e0493b40ec762a5dba7ee2cad528) crashes with something in my code.

**Comment by HavenDV** [comment]
Yes, I forgot to release new versions of Formatter packages after refactoring. Should be fixed in the latest version.

**Comment by AtleC** [comment]
Awesome, that worked 👍 

Looking further into it, there also seems like there is a way to [get the PID of the client process](https://stackoverflow.com/questions/60067804/c-sharp-interop-getnamedpipeclientprocessid-error-not-found-1168-0x490) 

`[DllImport("kernel32.dll", SetLastError = true)]
internal static extern bool GetNamedPipeClientProcessId(IntPtr Pipe, out int ClientProcessId);

int GetNamedPipeClientProcessId(NamedPipeServerStream pipeServer)
{
   var hPipe = pipeServer.SafePipeHandle.DangerousGetHandle();

    if (GetNamedPipeClientProcessId(hPipe, out var clientProcessId))
    {
        return clientProcessId;
    }
    else
    {
        var error = Marshal.GetLastWin32Error();
        return 0;
    }
}`

This works great if called straight from the NamedPipeServerStream, but this is not exposed in H.Pipes.

Could this also be implemented?
I took a stab at it myself but have not yet found a way to import GetNamedPipeClientProcessId into H.Pipes.
A possible solution could be to pass the NamedPipeServerStream into ConnectionEventArgs, but I guess that would be less than optimal.

**Comment by HavenDV** [comment]
I have moved PipeConnection.PipeStream to public properties for advanced use.
   
```csharp
/// <summary>
/// Raw pipe stream. You can cast it to <see cref="NamedPipeClientStream"/> or <see cref="NamedPipeServerStream"/>.
/// </summary>
public PipeStream PipeStream { get; }
 ```

**Comment by AtleC** [comment]
I found a way 🤡

I'm not quite sure were to place the dll reference, I did a temporary placement in EventExtensions.cs
`    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static extern bool GetNamedPipeClientProcessId(IntPtr Pipe, out int ClientProcessId);
`
and then just place this in PipeConnection.cs
`    /// <summary>
    /// Gets the process PID of the client on the other end of the pipe.
    /// </summary>
    /// <returns>The process PID of the client on the other end of the pipe.</returns>
    /// <exception cref="InvalidOperationException"><see cref="PipeStream"/> is not <see cref="NamedPipeServerStream"/>.</exception>
    /// <exception cref="InvalidOperationException">No pipe connections have been made yet.</exception>
    /// <exception cref="InvalidOperationException">The connected pipe has already disconnected.</exception>
    /// <exception cref="InvalidOperationException">The pipe handle has not been set.</exception>
    /// <exception cref="ObjectDisposedException">The pipe is closed.</exception>
    /// <exception cref="IOException">The pipe connection has been broken.</exception>
    /// <exception cref="IOException">The process PID of the client is longer than 19 characters.</exception>
    public int GetNamedPipeClientProcessId()
    {
        if (PipeStream is not NamedPipeServerStream serverStream)
        {
            throw new InvalidOperationException($"{nameof(PipeStream)} is not {nameof(NamedPipeServerStream)}.");
        }

        var hPipe = PipeStream.SafePipeHandle.DangerousGetHandle();

        if (EventExtensions.GetNamedPipeClientProcessId(hPipe, out var clientProcessId))
        {
            return clientProcessId;
        }
        else
        {
            var error = Marshal.GetLastWin32Error();
            return 0;
        }
    }
`

We can then call it the same way as GetImpersonationUserName

`                var test = args.Connection.GetNamedPipeClientProcessId();
`

**Comment by HavenDV** [comment]
I am guessing that you can just add an Extension method for the PipeConnection.
I don't want to add Win32 API calls to the library at the moment.

**Comment by AtleC** [comment]
Absolutely, thanks for all the help.
H.Pipes looks like a promising project 👍
