### ISSUE TITLE
PipesServer<T> doesn't work with custom PipeSecurity for .NET 6 - .NET 8

### ISSUE THREAD

**Issue by kateryna-novak** [HavenDV/H.Pipes#75]
When you need to connect to the `PipesServer<T>` with the custom `PipeSecutity` using the `SetPipeSecurity` method, you receive a "Pipe is closed" exception on the client side and a bunch of other exceptions on the server side. The same issue arises when you use the `EnableEncryption` extension method for the `PipesServer<T>.` 

Reason: starting from the .NET 6, initialization of the `NamedPipesStreamServer` with the `PipeSecutity` should be done via the `NamedPipeServerStreamAcl.Create` factory method. 

The bug appears the server and the client run with asymmetric rights. I.e., a client runs with user rights, and a server runs with elevated rights.

**Comment by HavenDV** [comment]
I made a small fix for this on top of your PR
https://github.com/HavenDV/H.Pipes/commit/e51545eb868b57d1449e3b064ff6bc59c8c5170d

Should be available on Nuget soon as version 2.2.0
